### ISSUE TITLE
Rename to riak-nodejs-client-examples for consistency

### ISSUE THREAD

**Issue by mbbroberg** [basho/riak-nodejs-client-examples#1]
I'm updating READMEs and found that the dotnet client has this URL: https://github.com/basho-labs/riak-dotnet-client-samples/

I'm going to make this issue a pre-req to the PR since it will link to a 404 for now.

**Comment by lukebakken** [comment]
Well ... the code in this repo is most like the code here:

https://github.com/basho/riak-dotnet-client/tree/develop/src/RiakClientExamples

Since both will have all code from the docs in them.

riak-dotnet-client-samples should either be rolled into RiakClientExamples or nuked. The code there is out of date.

I removed the link to it in the README.

**Comment by mbbroberg** [comment]
:+1: Glad to nuke it after looking for useful information to merge from there. Thanks!
